sudo: required
services:
  - docker

before_install:
  - docker build -t heenach112/react-test -f ./client/Dockerfile.dev 

script:
  - docker run heenach112/react-test npm test -- --coverage

after_success:
  - docker build -t heenach112/multi-client ./client
  - docker build -t heenach112/multi-worker ./worker
  - docker build -t heenach112/multi-server ./server
  - docker build -t heenach112/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push heenach112/multi-client
  - docker push heenach112/multi-server
  - docker push heenach112/multi-nginx
  - docker push heenach112/multi-worker
